name: Build and Push Docker Image

on:
  push:
    branches:
      - NavBar-Development # Trigger the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    # Step 3: Build the Docker image
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/sikh-events-app:latest ./apps/sikh-events-frontend/sikh-events-navBar

    # Step 4: Push the Docker image to Docker Hub
    - name: Push Docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/sikh-events-app:latest
